
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-api-service
  cloud:
    gateway:
      routes:
        - id : NODE-JS-EUREKA
          #uri: lb://NODE-JS-EUREKA
          uri: http://localhost:3000
          predicates:
            - Path=/node/**
#        - id : shop
#          uri: http://localhost:8091
#          predicates:
#            - Path=/shop/**
#          filters:
#            PrefixPath=/api
      metrics:
        enabled: true
