
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-api-service
#  cloud:
#    gateway:
#      routes:
#        - id : user
#          uri: http://localhost:8090
#          predicates:
#            - Path=/user/**
#        - id : shop
#          uri: http://localhost:8091
#          predicates:
#            - Path=/shop/**
#          filters:
#            PrefixPath=/api
#      metrics:
#        enabled: true
